### ISSUE TITLE
[tracking]: Release v0.21

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#1241]
Tracking issue for the 0.21 release of the jsonrpsee* crates.

- [x] https://github.com/paritytech/jsonrpsee/issues/1238
- [x] https://github.com/paritytech/jsonrpsee/issues/1233
- [x] https://github.com/paritytech/jsonrpsee/issues/1196
- [x] https://github.com/paritytech/jsonrpsee/issues/1195
- [x] https://github.com/paritytech/jsonrpsee/issues/870
- [x] https://github.com/paritytech/jsonrpsee/pull/1122
- [x] https://github.com/paritytech/jsonrpsee/pull/1227
- [x] https://github.com/paritytech/jsonrpsee/pull/1249

Depending on how long it takes we could wait until `async trait` hits stable but when I tested in jsonrpsee I ran into a GAT issues in rustc
