### ISSUE TITLE
tracking: release jsonrpsee 1.0

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#1292]
Tracking for releasing jsonrpsee 1.0,

jsonrpsee has been quite stable now and it's time to release 1.0 to avoid breaking the APIs anymore

- [ ] https://github.com/paritytech/jsonrpsee/issues/1289
- [ ] https://github.com/paritytech/jsonrpsee/issues/1257
- [ ] https://github.com/paritytech/jsonrpsee/issues/1291
- [ ] https://github.com/paritytech/jsonrpsee/issues/1229
- [ ] https://github.com/paritytech/jsonrpsee/issues/1054
