### ISSUE TITLE
[tracking issue]: release jsonrpsee 0.2

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#251]
- [x] refactor `ws client` (released alpha version on crates.io)
- [x] refactor `http client` (released alpha version on crates.io)
- [ ] api proc macros (release alpha version to support for clients but server support is missing), #221 
  - status: not active
  - priority: low
- [x] refactor `ws server` (integration currently ongoing)
- [x] refactor `http server` 
- [x] bring back `jsonrpsee root crate`,  #214
- [ ] integrate with servers with substrate to test it in production.
  -  status: in progress https://github.com/paritytech/substrate/pull/8783
  -  priority: high
- [x] server batch requests #277
- [ ] tests on jsonrpsee-types #276
  -  status: partly addressed by #325 #326 
  -  priority: high
- [x] server subscriptions need to take params into account #116
  -  status: merged #318 
  -  priority: high
- [x] register async methods on RpcModule #291 
  -  status: merged #327  
  -  priority: high
- [ ] refactor `rpc module` so that it can be reused by servers #328
  -  status: not active
  -  priority: mid
- [ ] unify duplicated JSON-RPC types #329
  -  status: not active
  -  priority: mid

**Comment by dvdplm** [comment]
@maciejhirsz can you update the above with your issues/prs when you get a chance please?

**Comment by popzxc** [comment]
@niklasad1 As you might have noticed, I'm in particular interested in bringing this crate closer to production.

Can you please provide the status of unresolved issues (e.g. are there some of them in progress or not), as well as their priorities? I'd be happy to help.

**Comment by niklasad1** [comment]
Sure, I have updated the unresolved issues and I hope it helps.

We welcome your help of course, thanks

**Comment by dvdplm** [comment]
Closing this as 0.2 has been released. The next release is tracked in #376. Items that did not made it into 0.2 are copied to the 0.3 release tracking ticket.
