### ISSUE TITLE
[tracking] Release jsonrpsee v0.4

### ISSUE THREAD

**Issue by dvdplm** [paritytech/jsonrpsee#416]
Tracking issue for the 0.4 release of the jsonrpsee* crates. Issues that did not make it in for 0.3 are copied here (0.3 tracking issue [here](https://github.com/paritytech/jsonrpsee/issues/376)).

- [ ] ergonomic macros for constructing `JsonRpcParams`, #275 
- [ ] support http redirects, #339
- [ ] refine api proc macros (version 0.3 added a good level of support but it is yet untested in substrate)
- [ ] Resource limiting, #203
