### ISSUE TITLE
[tracking] Release v0.8

### ISSUE THREAD

**Issue by dvdplm** [paritytech/jsonrpsee#573]
Tracking issue for the 0.8 release of the jsonrpsee* crates. Issues that did not make it in for 0.7 are copied here..

- [ ] Investigate https://github.com/paritytech/jsonrpsee/issues/450, possibly related to https://github.com/paritytech/jsonrpsee/issues/437
- [ ] https://github.com/paritytech/jsonrpsee/issues/482
- [ ] Investigate https://github.com/paritytech/jsonrpsee/issues/487
- [ ] https://github.com/paritytech/jsonrpsee/issues/302
- [x] https://github.com/paritytech/jsonrpsee/issues/627
- [ ] https://github.com/paritytech/jsonrpsee/issues/606
- [x] #649

**Comment by niklasad1** [comment]
v0.8 is released.
