### ISSUE TITLE
[tracking] Release v0.10

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#670]
Tracking issue for the 0.10 release of the jsonrpsee* crates. Issues that did not make it in for 0.9 are copied here..

- [x] https://github.com/paritytech/jsonrpsee/pull/717
- [x] https://github.com/paritytech/jsonrpsee/pull/721
- [x] https://github.com/paritytech/jsonrpsee/pull/719
- [x] https://github.com/paritytech/jsonrpsee/pull/718
- [x] https://github.com/paritytech/jsonrpsee/pull/708
- [x] https://github.com/paritytech/jsonrpsee/pull/711
- [x] https://github.com/paritytech/jsonrpsee/pull/693
- [ ]
