### ISSUE TITLE
[tracking] Release v1.0

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#736]
Tracking issue for the 1.0 release of the jsonrpsee* crates.

- [ ] https://github.com/paritytech/jsonrpsee/issues/735
- [ ] https://github.com/paritytech/jsonrpsee/issues/734
- [ ] https://github.com/paritytech/jsonrpsee/issues/699
- [ ] https://github.com/paritytech/jsonrpsee/issues/696
- [x] https://github.com/paritytech/jsonrpsee/issues/766
- [x] https://github.com/paritytech/jsonrpsee/issues/738
- [ ] https://github.com/paritytech/jsonrpsee/issues/770
- [ ] https://github.com/paritytech/jsonrpsee/issues/758
- [ ] https://github.com/paritytech/jsonrpsee/issues/771

**Comment by jsdw** [comment]
I added a 1.0 milestone to represent this, so I'll close this now.
